version: '3.5'

# docker-compose pull
services:
  ypass_api_service:
    image: docker.io/jadelaw2876/websocket:test
    container_name: ypass_api_service

    expose:
      - 8000
    ports:
      - 8000:8000
    restart: unless-stopped

    # build: 
    #   context: ./websocket_latest
    #   dockerfile: ./Dockerfile
    
    # for simulatanous container operation
    tty: true 
    volumes:
      - ./app:/usr/local.////////
  
    networks:
      - ypass_net
  
  cu_client:
    image: docker.io/jadelaw2876/cuclient:test
    container_name: cu_client
    # build: 
    #   context: ./CU_client
    #   dockerfile: ./Dockerfile

    networks:
      - ypass_net
  
  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx_proxy
    ports:
      - 8080:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      # - ./share/config.txt:/share/config.txt
    networks:
      - ypass_net

  # mongodb:


networks:
  ypass_net:
    driver: bridge
    external: true
